apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql8:3306"
  database: "msvc_usuarios"
  username: "root"
  password: "1234"
  cursos_url: "msvc-cursos:8002"
  msvc-usuarios.yml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres16:5432"
  database: "msvc_cursos"
  username: "postgres"
  password: "1234"
  usuario_url: "msvc-usuarios:8001"