services:
  postgres16:
    container_name: postgres16
    image: postgres:16-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-cursos:
    container_name: msvc-cursos
    image: cifuentesd05/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres16:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USUARIOS_URL: ec2-44-220-130-39.compute-1.amazonaws.com:8001
    #env_file:
    #  - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres16
     # - msvc-usuarios
    restart: always

volumes:
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring