services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: msvc_usuarios     #Tambien se pueden declarar de esta forma -MYSQL_DATABASE=msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart : always
    networks:
      - spring      #Las redes en compose ya vienen por defecto, por lo que declarlas explicitamente esta de mas

  postgres16:
    container_name: postgres16
    image: postgres:16-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: cifuentesd05/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment: #env_file: ./msvc-usuarios/.env
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: 1234
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
    image: cifuentesd05/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres16:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      USUARIOS_URL: msvc-usuarios:8001
    #env_file:
    #  - ./msvc-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres16
      - msvc-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring