services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: msvc_usuarios     #Tambien se pueden declarar de esta forma -MYSQL_DATABASE=msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart : always
    networks:
      - spring      #Las redes en compose ya vienen por defecto, por lo que declarlas explicitamente esta de mas
  msvc-usuarios:
    container_name: msvc-usuarios
    image: cifuentesd05/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment: #env_file: ./msvc-usuarios/.env
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: 1234
      CURSOS_URL: ec2-52-91-184-233.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
volumes:
  data-mysql:
    name: data-mysql
networks:
  spring:
    name: spring